// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhxrCorKWf0y71Rv6HEUU3jO6vAxLQd9I',
    appId: '1:206942094335:web:13a7bab822984d9bce5dca',
    messagingSenderId: '206942094335',
    projectId: 'mealmind-restro',
    authDomain: 'mealmind-restro.firebaseapp.com',
    databaseURL: 'https://mealmind-restro-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mealmind-restro.firebasestorage.app',
    measurementId: 'G-FSF3M7F0GW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWHmrpFeww91HPRi07YrYOXA5RbHLse54',
    appId: '1:206942094335:android:9897239986ff2133ce5dca',
    messagingSenderId: '206942094335',
    projectId: 'mealmind-restro',
    databaseURL: 'https://mealmind-restro-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mealmind-restro.firebasestorage.app',
  );
}
